aq: 0.0.1

info:
  id: aq.apps.ideas.personas
  version: 1.0.0
  title: Idea Generator
  profile: >
    You are a expert in product innovation.

models:
  gpt4:
    model: gpt-4-0125-preview
    provider: openai

activities:
  read_prompt:
    type: read

  generate_personas:
    type: generate
    inputs:
      - activity: read_prompt
    models:
      - gpt4
    parameters:
      temperature: 0.7
      format: json
      prompt: >
        We are generating ideas for a new product described as:
        
        {{read_prompt}}
        
        Come up with a list of 10 greatest inventors and product innovators of all time
        who could contribute product ideas that match these requirements. 

        Include only the name of the inventor in the result. 

        Sample output: 

        ["Thomas Edison", "Nikola Tesla", "Leonardo da Vinci", "Steve Jobs"]


  generate_ideas:
    type: generate
    inputs:
      - activity: read_prompt
      - activity: generate_personas
        map: $
    models:
      - gpt4
    parameters:
      temperature: 0.7
      max_tokens: 2000
      format: json
      prompt: >
        Think like {{generate_personas}}, one of the greatest inventors and product innovators of all time.

        Generate 10 ideas for a new product with the following requirements:
        
        {{read_prompt}}

        The ideas are just ideas. The product need not yet exist, nor may it necessarily be
        clearly feasible.
        
        Follow these steps. Do each step, even if you think you do not need to.
        
        First generate a list of 10 ideas (short title only).
        
        Second, go through the list and determine whether the ideas are different and bold,
        modify the ideas as needed to make them bolder and more different. No two ideas
        should be the same. This is important!

        Do this step by step! 

        Produce the result as a list of JSON objects. 
        Include the name of the inventor and the idea in each entry.
        Do not include intermediate results, only the final ones, in your output.
        
        Sample output: 
        
        [{
          "idea": "Coffee mug that heats beverages", 
          "inventor": "{{generate_personas}}"
        }, {
          "idea": "Study lamp with Pomodoro timer",
          "inventor": "{{generate_personas}}"
        }]

  add_names_and_descriptions:
    type: generate
    inputs:
      - activity: read_prompt
      - activity: generate_ideas
        map: $
        batch_size: 10
    models:
      - gpt4
    parameters:
      temperature: 0.7
      format: json
      max_tokens: 2000
      prompt: >
        We asked famous inventors and product innovators of all times 
        to generate ideas for a new product described as:
        {{read_prompt}}

        Here is a list of ideas that were generated for this product:
        {{generate_ideas}}

        Think like the idea's inventor, and give each idea a name and a description.
        The description should be expressed as a paragraph of 40-80 words.
        
        Sample input: 
        
        [{
          "idea": "Coffee mug that heats beverages", 
          "inventor": "Inventor Name"
        }, {
          "idea": "Study lamp with Pomodoro timer",
          "inventor": "Inventor Name"
        }]
        
        Sample output: 
        
        [{
          "name": "QuickHeat Mug",
          "inventor": "Inventor Name",
          "description": "An insulated, battery-powered coffee mug that can heat beverages within minutes and maintain the temperature. Ideal for students who need a warm drink during long study sessions but don't have immediate access to a kitchen."
        }, {
          "name": "StudyBuddy Lamp"
          "inventor": "Inventor Name",
          "description": "A compact, portable LED desk lamp with built-in timers for the Pomodoro study technique, adjustable brightness levels, and a USB charging port for smartphones. It's designed to help students focus and manage their study time effectively."
        }]
        
  save_ideas:
    type: write
    inputs:
      - activity: add_names_and_descriptions
    parameters:
      format: json        
      filename: personas.json
        